# Generated by Django 5.1.2 on 2024-10-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0002_remove_aluno_frequencia_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='media_frequencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aluno',
            name='media_notas',
            field=models.FloatField(default=0.0),
        ),
    ]
